name: dcrup
base: core22
version: '0.6.9'
summary: Cargo-like utility to manage C/C++ projects
description: |
  A build tool and package manager for C/C++ projects inspired by Rust's Cargo.

grade: stable
confinement: classic

apps:
  dcr:
    command: bin/dcr

parts:
  dcr:
    plugin: dump
    source: dist/