file_dcr_toml: str = """[package]
name = "{project_name}"
version = "{project_version}"
language = "{project_language}"
compiler = "{project_compiler}"

[dependencies]
"""
file_main_c: str = """#include <stdio.h>

int main(void) {
    printf("Hello World!\\n");
    return 0;
}
"""

file_dcr_lock: str = """# This file is automatically @generated by dcr.
# It is not intended for manual editing.
version = 1

[[package]]
name = "{project_name}"
version = "{project_version}"
"""

"""[[package]]
name = "{package_name}"
version = "{package_version}"
source = "{{package_source}"
checksum = "{package_checksum}"
dependencies = [{package_dependencies}]"""

project_version: str = "0.1.0"
project_language: str = "c"
project_compiler: str = "clang"

profile: str = "debug"
c_comp: str = "clang"
flags: dict[str, list[str]] = {
    "release": ["-O3", "-DNDEBUG", "-march=native"],
    "debug": ["-O0", "-g", "-Wall", "-Wextra", "-fno-omit-frame-pointer", "-DDEBUG"],
}
